---
title: "パッケージインストーラー"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Japanese Only, in this repository. 


# Introduction
本リポジトリはR/RStudioをインストールした直後、または、メジャーアップデートした直後に普段利用しているパッケージをインストールするためのスクリプトとデータを整理しているリポジトリです。  

インストールするパッケージは、 [データ分析勉強会 <i class="fa fa-external-link"></i>](https://sites.google.com/site/kantometrics/home){target="_blank" title="Google site"} で必要になるパッケージが中心です。なお、パッケージに必要なライブラリなど（javaやOSのライブラリなど）のインストールは行いませんので、必要な場合はパッケージインストール前に別途インストールしてください。  

　  

## Packages
利用目的に応じて以下からインストールできます。

Type  | Description
------|------------------------------------------------------------------------
tidyverse | rocker/tidyverse相当のパッケージをインストール
verse     | rocker/verse相当のパッケージをインストール
mlwr      | verseに『Rによる機械学習』のサンプルコードの実行に必要なパッケージをインストール
tidymodels | mlwrに`tidymodels`パッケージをインストール
tools     | 便利なパッケージ類を追加インストール



## How to use

チュートリアルを実行するにはローカルに本リポジトリのファイルが必要です。


1. 本リポジトリをクローンします
1. クローンしたフォルダをプロジェクトフォルダに指定しプロジェクトを作成します
1. RStudioから作成したプロジェクトを開きます
1. **[File]** ペインから任意のチュートリアルファイルを開きます
1. エディタ上段に表示される **[Run Document]** というボタンをクリックします
1. チュートリアルファイルがレンダリングされ **[Viewer]** ペインにチュートリアルが表示されます


チュートリアルの実行にはローカルホスト(127.0.0.1)上の`shiny`サーバが利用されていますので、[Viewer]ペインにある **[Show in new window]** をクリックしてブラウザ上で実行することも可能です。  
　  
`git`を使うのが難しい場合は、以下の手順で実行してください


1. RStudioで任意のプロジェクトを作成します
1. 本リポジトリをZIP形式でダウンロードします
1. ダウンロードしたZIP形式のファイルの中身をプロジェクトフォルダにコピーします
1. [File]ペインから任意のチュートリアルファイルを開きます
1. エディタ上段に表示される **[Run Document]** というボタンをクリックします
1. チュートリアルファイルがレンダリングされ[Viewer]ペインにチュートリアルが表示されます


## チュートリアルの使い方
* **[Code]** と左上に書いてある欄に実行コードを記述し右側の **[Run Code]** ボタンを押せば記述した（記述されている)
コードが実行されます。
* コードが間違っている場合はエラーが表示されます。
* 一部のコードは既に記述済ですが、コードを追加・記入したい場合は最終行の行末にカーソルを持っていき改行することでコードの追加ができます。
* 学習結果は記録されますがリセットしたい場合は左側見出しのの一番下にある **[Start Over]** をクリックしてください。


　  
以上


　  
不明点は [データ分析勉強 <i class="fa fa-external-link"></i>](https://sites.google.com/site/kantometrics/home){target="_blank" title="Google site"} まで、または、本リポジトリのissues にて問い合わせください。